### ISSUE TITLE
STEditor font not proportional to environment font

### ISSUE THREAD

**Issue by nmingotti** [bpieber/Cuis-Smalltalk-StyledTextEditor#28]
Hi, 

I am new to Smalltalk, I started my explorations with Squeak. 

Today I installed Cuis to see your StyledTextEditor, which is a terrific idea IMO, it may be extremely useful to write wonderful documentation, maybe near methods! 

I installed Cuis and STE, all fine, but there is a problem, the font is way toooo small when compared to the Workspace default font. I tried to tune it a bit without much success, I need the font considerablly larger. Is it possible? 

![image](https://user-images.githubusercontent.com/7042178/64092366-5cfd1380-cd09-11e9-8bcd-499fb69c66c3.png)

**Comment by jvuletich** [comment]
Hi Nicola.

Yes. After installing large fonts and StyledTextEditor, you need to edit #createSampleParagraphStyleSet, and make the family name be 'DejaVu Sans' (instead of 'DejaVu') and pick a larger size, for example 21 (instead of 11 for 'Normal'). Do the same for the rest of the paragraph styles, and also for #createSampleCharacterStyleSet if you are using Character styles.

After that, open a new StyledTextEditor and it will use the larger fonts.

BTW, keep in mind that the most update version of StyledTextEditor is the one at the Cuis Smalltalk organization: https://github.com/Cuis-Smalltalk/StyledTextEditor and not this one.

**Comment by nmingotti** [comment]
Hi Juan,

thank you for your help ! 

I tried, it works. I signal you that there is a little anomaly though. Where there is written "Paragraph style" i guess it should scale with the Window title "Styled Text Editor" but it does not. I attach picture. 
It is not fundamental, just a detail. Much more important was the text size where I write, and that works. 

About the lastest release of STE, I saw it, I am using yours. But, in your fork there isn't possibility of typing new Issues, so I wrote here. I am not expert of GitHub, maybe I just do not know where to click. 

![image](https://user-images.githubusercontent.com/7042178/64162173-b17cbd80-cdf3-11e9-84f3-b45079f584da.png)

**Comment by jvuletich** [comment]
Hi Nicolas, I just pushed some changes for the visual glitches you reported, and a few others. Now, upon StyledTextInstaller package install, you'll also get the nicer TrueType fonts, even if you haven't selected "Huge Fonts".
I also enabled the Issue Tracker at https://github.com/Cuis-Smalltalk/StyledTextEditor , so problems can be reported there.
Thanks!
